import type { Product } from '@/lib/types/product'
import { publicPath } from '@/lib/paths'
import { buildUrinalLineColors } from '@/lib/product-variants'

const shop = (path: string) => path

export const products: Product[] = [
  {
    slug: 'xcren-hd',
    nameKey: 'products.xcrenHd.name',
    categoryKey: 'products.xcrenHd.category',
    badgeKey: 'products.xcrenHd.badge',
    shortDescriptionKey: 'products.xcrenHd.short',
    longDescriptionKey: 'products.xcrenHd.long',
    benefitKeys: [
      'products.xcrenHd.benefits.0',
      'products.xcrenHd.benefits.1',
      'products.xcrenHd.benefits.2',
      'products.xcrenHd.benefits.3',
      'products.xcrenHd.benefits.4',
      'products.xcrenHd.benefits.5',
      'products.xcrenHd.benefits.6',
      'products.xcrenHd.benefits.7',
      'products.xcrenHd.benefits.8',
      'products.xcrenHd.benefits.9',
    ],
    useCaseKeys: [
      'products.xcrenHd.useCases.0',
      'products.xcrenHd.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Xcren HD', 'PhotoStock', 'XHD-3B-V0 .png'),
    colors: buildUrinalLineColors('XHD', 'xhd', ['products', 'Xcren HD']),
    shopPath: shop('/collections/xcren-hd'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: true,
  },
  {
    slug: 'ekcoscreen',
    nameKey: 'products.ekcoscreen.name',
    categoryKey: 'products.ekcoscreen.category',
    shortDescriptionKey: 'products.ekcoscreen.short',
    longDescriptionKey: 'products.ekcoscreen.long',
    benefitKeys: [
      'products.ekcoscreen.benefits.0',
      'products.ekcoscreen.benefits.1',
      'products.ekcoscreen.benefits.2',
    ],
    useCaseKeys: [
      'products.ekcoscreen.useCases.0',
      'products.ekcoscreen.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Ekcoscreen', 'PhotoStock', 'EKS-3B-V0.png'),
    colors: buildUrinalLineColors('EKS', 'eks', ['products', 'Ekcoscreen']),
    shopPath: shop('/collections/ekcoscreen'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: true,
  },
  {
    slug: 'powerscreen',
    nameKey: 'products.powerscreen.name',
    categoryKey: 'products.powerscreen.category',
    shortDescriptionKey: 'products.powerscreen.short',
    longDescriptionKey: 'products.powerscreen.long',
    benefitKeys: [
      'products.powerscreen.benefits.0',
      'products.powerscreen.benefits.1',
      'products.powerscreen.benefits.2',
    ],
    useCaseKeys: [
      'products.powerscreen.useCases.0',
      'products.powerscreen.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Powerscreen', 'PhotoStock', 'PWR-3B-V0.png'),
    colors: buildUrinalLineColors('PWR', 'pwr', ['products', 'Powerscreen']),
    shopPath: shop('/collections/powerscreen'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: true,
  },
  {
    slug: 'basic-screen',
    nameKey: 'products.basicScreen.name',
    categoryKey: 'products.basicScreen.category',
    shortDescriptionKey: 'products.basicScreen.short',
    longDescriptionKey: 'products.basicScreen.long',
    benefitKeys: [
      'products.basicScreen.benefits.0',
      'products.basicScreen.benefits.1',
      'products.basicScreen.benefits.2',
    ],
    useCaseKeys: [
      'products.basicScreen.useCases.0',
      'products.basicScreen.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Basic Screen', 'PhotoStock', 'BS-3B-V0.png'),
    colors: buildUrinalLineColors('BS', 'bs', ['products', 'Basic Screen']),
    shopPath: shop('/collections/basic-screen'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: false,
  },
  {
    slug: 'urolite',
    nameKey: 'products.urolite.name',
    categoryKey: 'products.urolite.category',
    shortDescriptionKey: 'products.urolite.short',
    longDescriptionKey: 'products.urolite.long',
    benefitKeys: [
      'products.urolite.benefits.0',
      'products.urolite.benefits.1',
      'products.urolite.benefits.2',
    ],
    useCaseKeys: [
      'products.urolite.useCases.0',
      'products.urolite.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Urolite', 'PhotoStock', 'ULT-3B-V0.png'),
    colors: buildUrinalLineColors('ULT', 'ult', ['products', 'Urolite']),
    shopPath: shop('/collections/urolite'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: true,
  },
  {
    slug: 'ekco-clip',
    nameKey: 'products.ekcoClip.name',
    categoryKey: 'products.ekcoClip.category',
    shortDescriptionKey: 'products.ekcoClip.short',
    longDescriptionKey: 'products.ekcoClip.long',
    benefitKeys: [
      'products.ekcoClip.benefits.0',
      'products.ekcoClip.benefits.1',
      'products.ekcoClip.benefits.2',
    ],
    useCaseKeys: [
      'products.ekcoClip.useCases.0',
      'products.ekcoClip.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Ekcoclip', 'PhotoStock', 'TBC-3B-V0.png'),
    colors: buildUrinalLineColors('TBC', 'tbc', ['products', 'Ekcoclip']),
    shopPath: shop('/collections/ekco-clip'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: false,
  },
  {
    slug: 'fresh-drop',
    nameKey: 'products.freshDrop.name',
    categoryKey: 'products.freshDrop.category',
    shortDescriptionKey: 'products.freshDrop.short',
    longDescriptionKey: 'products.freshDrop.long',
    benefitKeys: [
      'products.freshDrop.benefits.0',
      'products.freshDrop.benefits.1',
      'products.freshDrop.benefits.2',
    ],
    useCaseKeys: [
      'products.freshDrop.useCases.0',
      'products.freshDrop.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Freshdrop', 'PhotoStock', 'FDI-3B-V0.png'),
    colors: buildUrinalLineColors('FDI', 'fdi', ['products', 'Freshdrop']),
    fragrances: [
      { id: 'fresh', labelKey: 'products.fragrances.fresh' },
      { id: 'citrus', labelKey: 'products.fragrances.citrus' },
    ],
    shopPath: shop('/collections/fresh-drop'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: false,
  },
  {
    slug: 'ez-trap',
    nameKey: 'products.ezTrap.name',
    categoryKey: 'products.ezTrap.category',
    shortDescriptionKey: 'products.ezTrap.short',
    longDescriptionKey: 'products.ezTrap.long',
    benefitKeys: [
      'products.ezTrap.benefits.0',
      'products.ezTrap.benefits.1',
      'products.ezTrap.benefits.2',
    ],
    useCaseKeys: [
      'products.ezTrap.useCases.0',
      'products.ezTrap.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'EzTrap', 'PhotoStock', 'EZT-1P-V0.png'),
    colors: [
      {
        id: 'ezt-with-tool',
        sku: 'EZT-01',
        labelKey: 'products.ezTrap.variants.withTool',
        swatchHex: '#0F68B2',
        imageSrc: publicPath('products', 'EzTrap', 'PhotoStock', 'EZT-1P-V0.png'),
      },
      {
        id: 'ezt-without-tool',
        sku: 'EZT-00',
        labelKey: 'products.ezTrap.variants.withoutTool',
        swatchHex: '#575756',
        imageSrc: publicPath('products', 'EzTrap', 'PhotoStock', 'EZT-1P-V1.jpg'),
      },
    ],
    shopPath: shop('/collections/ez-trap'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: false,
  },
  {
    slug: 'xcren-puck',
    nameKey: 'products.xcrenPuck.name',
    categoryKey: 'products.xcrenPuck.category',
    shortDescriptionKey: 'products.xcrenPuck.short',
    longDescriptionKey: 'products.xcrenPuck.long',
    benefitKeys: [
      'products.xcrenPuck.benefits.0',
      'products.xcrenPuck.benefits.1',
      'products.xcrenPuck.benefits.2',
    ],
    useCaseKeys: [
      'products.xcrenPuck.useCases.0',
      'products.xcrenPuck.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Xcren Puck', 'PhotoStock', 'XPU-1P-V0.png'),
    defaultColorId: 'xpu-02b',
    colors: [
      {
        id: 'xpu-02b',
        sku: 'XPU-02B',
        labelKey: 'products.xcrenPuck.variants.blueFresh',
        swatchHex: '#0F68B2',
        imageSrc: publicPath('products', 'Xcren Puck', 'PhotoStock', 'XPU-1P-V0.png'),
      },
      {
        id: 'xpu-01w',
        sku: 'XPU-01W',
        labelKey: 'products.xcrenPuck.variants.whiteFresh',
        swatchHex: '#ECEFF1',
        imageSrc: publicPath('products', 'Xcren Puck', 'PhotoStock', 'XPU-2G-V0.png'),
      },
    ],
    shopPath: shop('/collections/xcren-puck'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: false,
  },
  {
    slug: 'ekco-mat',
    nameKey: 'products.ekcoMat.name',
    categoryKey: 'products.ekcoMat.category',
    shortDescriptionKey: 'products.ekcoMat.short',
    longDescriptionKey: 'products.ekcoMat.long',
    benefitKeys: [
      'products.ekcoMat.benefits.0',
      'products.ekcoMat.benefits.1',
      'products.ekcoMat.benefits.2',
    ],
    useCaseKeys: [
      'products.ekcoMat.useCases.0',
      'products.ekcoMat.useCases.1',
    ],
    heroImageSrc: publicPath('products', 'Ekcomat', 'PhotoStock', 'UFM-1P-V0.png'),
    colors: [
      {
        id: 'ufm-01',
        sku: 'UFM-01',
        labelKey: 'products.ekcoMat.variants.standard',
        swatchHex: '#0F68B2',
        imageSrc: publicPath('products', 'Ekcomat', 'PhotoStock', 'UFM-1P-V0.png'),
      },
    ],
    shopPath: shop('/collections/ekco-mat'),
    brandingAvailable: true,
    ecoOneCompatible: true,
    featured: false,
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}
